import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full bg-cyan-400 p-4 items-center justify-around">
          <Link href="/">Home</Link>
          <Link href="/create">create</Link>
          <Link href="/update">update</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
